description: |
  Allows the stock kubectl client to work with Amazon EKS.
  Installs the AWS CLI, the AWS IAM Authenticator for Kubernetes and
  updates the kubectl configuration file to use the AWS IAM Authenticator.
parameters:
  label:
    description: |
      Description the command line.
    type: string
    default: "Update the kubectl configuration file to use the authenticator"
  cluster-name:
    description: |
      The name of the cluster for which to create a kubeconfig entry.
    type: string
  aws-region:
    description: |
      The AWS region that the cluster is in. If not specified, the configured default
      region for your AWS CLI installation will be used.
    type: string
    default: ""
  aws-profile:
    description: |
      The AWS profile to be used. If not specified, the configured default
      profile for your AWS CLI installation will be used.
    type: string
    default: ""
  kubeconfig-file-path:
    description: |
      Specifies a kubeconfig file to append the configuration details to.
      By default, the configuration is written to the first file path in the
      KUBECONFIG environment variable (if it is set) or the default kubeconfig
      path (.kube/config) in your home directory.
    type: string
    default: ""
  cluster-authentication-role-arn:
    description: |
      To assume a role for cluster authentication, specify an IAM role ARN with
      this option. For example, if you created a cluster while assuming an IAM
      role, then you must also assume that role to connect to the cluster the
      first time.
    type: string
    default: ""
  cluster-context-alias:
    description: |
      Alias for the cluster context name. If a value is not specified,
      the cluster context name will be set to match the cluster ARN.
    type: string
    default: ""
  dry-run:
    description: |
      Print the merged kubeconfig to stdout instead of writing it to file.
    type: boolean
    default: false
  verbose:
    description: |
      Print more detailed output when writing to the kubeconfig file.
    type: boolean
    default: false
  aws-oidc-role:
    description: IAM role ARN for OIDC
    type: string
    default: ""
steps:
  - run:
      name: "<< parameters.label >>"
      command: |
        CLUSTER_NAME="<< parameters.cluster-name >>"
        AWS_REGION="<< parameters.aws-region >>"
        AWS_PROFILE="<< parameters.aws-profile >>"
        KUBECONFIG_FILE_PATH="<< parameters.kubeconfig-file-path >>"
        ROLE_ARN="<< parameters.cluster-authentication-role-arn >>"
        CLUSTER_CONTEXT_ALIAS="<< parameters.cluster-context-alias >>"
        DRY_RUN="<< parameters.dry-run >>"
        VERBOSE="<< parameters.verbose >>"
        OIDC_ROLE_ARN="<< parameters.aws-oidc-role >>"
        if [ -n "${CLUSTER_NAME}" ]; then
          set -- "$@" --name "${CLUSTER_NAME}"
        fi
        if [ -n "${AWS_REGION}" ]; then
          set -- "$@" --region "${AWS_REGION}"
        fi
        if [ -n "${AWS_PROFILE}" ]; then
          set -- "$@" --profile "${AWS_PROFILE}"
        fi
        if [ -n "${KUBECONFIG_FILE_PATH}" ]; then
          set -- "$@" --kubeconfig "${KUBECONFIG_FILE_PATH}"
        fi
        if [ -n "${ROLE_ARN}" ]; then
          set -- "$@" --role-arn "${ROLE_ARN}"
        fi
        if [ -n "${CLUSTER_CONTEXT_ALIAS}" ]; then
          set -- "$@" --alias "${CLUSTER_CONTEXT_ALIAS}"
        fi
        if [ "${DRY_RUN}" == "true" ]; then
          set -- "$@" --dry-run
        fi
        if [ "${VERBOSE}" == "true" ]; then
          set -- "$@" --verbose
        fi
        if [ -n "${OIDC_ROLE_ARN}" ]; then
          echo "Assuming role using OIDC..."
          AWS_ROLE_SESSION_NAME="circleci-session"
          CREDS=$(aws sts assume-role-with-web-identity --role-arn ${OIDC_ROLE_ARN} --role-session-name ${AWS_ROLE_SESSION_NAME} --web-identity-token ${CIRCLE_OIDC_TOKEN} --duration-seconds 3600)
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.Credentials.AccessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.Credentials.SessionToken')
        fi
        aws eks update-kubeconfig "$@"
